from collections.abc import Callable, Sequence

import numpy as np
from numpy.typing import NDArray

N_COLS: int
N_ROWS: int
BUF_N_CHANNELS: int
__all__: list[str]

class GameMetadata:
    def __init__(self, game_id: int, player0_id: int, player1_id: int) -> None: ...
    @property
    def game_id(self) -> int: ...
    @property
    def player0_id(self) -> int: ...
    @property
    def player1_id(self) -> int: ...

class GameRequest:
    def __init__(
        self, metadata: GameMetadata, opening_moves: Sequence[int] = ...
    ) -> None: ...
    @property
    def metadata(self) -> GameMetadata: ...
    @property
    def opening_moves(self) -> list[int]: ...

class SelfPlayOptions:
    def __init__(self) -> None: ...
    max_nn_batch_size: int
    n_mcts_iterations: int
    c_exploration: float
    c_ply_penalty: float
    root_dirichlet_alpha: float
    root_dirichlet_epsilon: float
    temperature_midpoint_ply: int
    temperature_cutoff_ply: int
    early_temperature: float
    middle_temperature: float
    late_temperature: float
    seed: int
    worker_threads: int

class GameSnapshot:
    @property
    def board(self) -> list[list[int]]: ...
    @property
    def legal_moves(self) -> tuple[bool, bool, bool, bool, bool, bool, bool]: ...
    @property
    def side_to_move(self) -> str: ...
    @property
    def terminal_state(self) -> str: ...
    @property
    def winning_cells(self) -> list[tuple[int, int]]: ...
    @property
    def move_history(self) -> list[int]: ...
    @property
    def policy(self) -> tuple[float, float, float, float, float, float, float]: ...
    @property
    def q_penalty(self) -> float: ...
    @property
    def q_no_penalty(self) -> float: ...
    @property
    def n_mcts_iterations(self) -> int: ...
    @property
    def max_mcts_iterations(self) -> int: ...
    @property
    def c_exploration(self) -> float: ...
    @property
    def c_ply_penalty(self) -> float: ...
    @property
    def background_running(self) -> bool: ...

class InteractivePlay:
    def __init__(
        self,
        py_eval_pos_cb: EvalCallback,
        max_mcts_iters: int,
        c_exploration: float,
        c_ply_penalty: float,
        red_model_id: int = 0,
        gold_model_id: int = 0,
    ) -> None: ...
    def snapshot(self) -> GameSnapshot: ...
    def make_move(self, column: int) -> bool: ...
    def make_best_move(self) -> bool: ...
    def make_best_move_if_ready(self) -> bool: ...
    def make_random_move(self, temperature: float = 1.0) -> bool: ...
    def increase_mcts_iterations(self, count: int) -> None: ...
    def undo(self) -> bool: ...
    def reset(self) -> None: ...
    def retry_evaluation(self) -> None: ...
    def close(self) -> None: ...

class Sample:
    @property
    def ply(self) -> int: ...
    def flip_h(self) -> Sample: ...
    def to_numpy(
        self,
    ) -> tuple[
        NDArray[np.float32],
        NDArray[np.float32],
        NDArray[np.float32],
        NDArray[np.float32],
    ]: ...
    def pos_str(self) -> str: ...

class GameResult:
    @property
    def metadata(self) -> GameMetadata: ...
    @property
    def samples(self) -> list[Sample]: ...
    def player0_score(self) -> float: ...

class PlayGamesResult:
    def __init__(self) -> None: ...
    @property
    def results(self) -> list[GameResult]: ...
    def __add__(self, other: PlayGamesResult) -> PlayGamesResult: ...
    def split_games(self, chunk_size: int) -> list[PlayGamesResult]: ...
    def split_train_test(
        self, train_frac: float, seed: int
    ) -> tuple[list[Sample], list[Sample]]: ...
    def score_policies(
        self,
        solver_path: str,
        solver_book_path: str,
        solution_cache_path: str,
    ) -> float: ...
    def unique_positions(self) -> int: ...
    def to_cbor(self) -> bytes: ...
    @staticmethod
    def from_cbor(data: bytes) -> PlayGamesResult: ...

EvalCallback = Callable[
    [int, NDArray[np.float32]],
    tuple[NDArray[np.float32], NDArray[np.float32], NDArray[np.float32]],
]
SelfPlayTelemetryCallback = Callable[[dict[str, int | float | bool]], None]

def play_games(
    reqs: Sequence[GameMetadata],
    max_nn_batch_size: int,
    n_mcts_iterations: int,
    c_exploration: float,
    c_ply_penalty: float,
    py_eval_pos_cb: EvalCallback,
    progress_callback: Callable[[int, int], None] | None = None,
    cancelled_callback: Callable[[], bool] | None = None,
) -> PlayGamesResult: ...
def play_games_v2(
    requests: Sequence[GameRequest],
    options: SelfPlayOptions,
    py_eval_pos_cb: EvalCallback,
    progress_callback: Callable[[int, int], None] | None = None,
    cancelled_callback: Callable[[], bool] | None = None,
    telemetry_callback: SelfPlayTelemetryCallback | None = None,
) -> PlayGamesResult: ...
def run_tui(
    py_eval_pos_cb: EvalCallback,
    max_mcts_iters: int,
    c_exploration: float,
    c_ply_penalty: float,
    auto_red: bool = False,
    auto_blue: bool = False,
) -> None: ...
